<a href="https://colab.research.google.com/github/R-kumarrrr/Python/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Print

In [ ]:
print('Hello World')

Hello World


# Variable

In [ ]:
Name = 'Rajat Dahiya'
Age = 21
Salary = 12.5
print(Name, Age, Salary)
print(type(Name))

Rajat Dahiya 21 12.5
<class 'str'>


# Sum

In [ ]:
a,b = 12,23
Sum = a + b
print(Sum)

35


# Comments

In [ ]:
# This is a single line comment
'''
This is a
multi line
comment
'''

# Type Conversion

In [ ]:
# This is done by the interpreter automatically
a,b = 12,23.5
sum = a + b
print(sum)  # this is give a float value because float is superior than int

c,d = 23,'5'
sum1 = c+d
#print(sum1) this will give an error because int and str cant be added

35.5


# Type Casting

In [ ]:
# This is done by the user manually
c,d = 23,'5'
sum1 = c+int(d)
print(sum1)

28


# Input

In [ ]:
# By default it will take Str as the datatype
Number = int(input('Enter a number: '))
print(Number)

Enter a number: 21
21


# Q1 : Sum

In [ ]:
Num1 = int(input('Enter a number: '))
Num2 = int(input('Enter a number: '))
Sum = Num1 + Num2
print(Sum)

Enter a number: 21
Enter a number: 23
44


# Q2 : Area

In [ ]:
Side = int(input('Enter a number: '))
Area = Side * Side
print(Area)

Enter a number: 25
625


# Q3 : Average of Float

In [ ]:
num_float1 = float(input('Enter a number: '))
num_float2 = float(input('Enter a number: '))
num_float3 = float(input('Enter a number: '))
Average = (num_float1 + num_float2 + num_float3)/3
print(Average)

Enter a number: 12
Enter a number: 224
Enter a number: 46
94.0


# Q4 : If else

In [ ]:
num1 = int(input('Enter a number: '))
num2 = int(input('Enter a number: '))
if num1 > num2:
    print('True')
else:
    print('False')

Enter a number: 12
Enter a number: 23
False


# String Functions

In [ ]:
str1 = 'hello World'
str1.capitalize()
str1.upper()
str1.lower()
str1.title()
str1.swapcase()
str1.find('World')
len(str1)
str1.replace('World','Rajat')
str1.count('l')

'hello Rajat'

# Indexing

In [ ]:
name = 'rahat kumar'
name[0]
# name[2] = 'j' str doesn't allow item assignment

'r'

# Slicing

In [ ]:
name[0:5]
name[:9]
name[2:7]
name[-5:-1]
name[::-1]

'ramuk tahar'

# Q5 : Print And Length

In [ ]:
Nam = input('Enter you name: ')
print(len(Nam))

Enter you name: Rajat kumar
11


# Q6 : Even Odd

In [ ]:
checkingNum = int(input('Enter a number: '))
if checkingNum % 2 == 0:
    print('Even')
else:
    print('Odd')

Enter a number: 23
Odd


# Q7 : Largest Num

In [ ]:
Numb1 = int(input('Enter a number: '))
Numb2 = int(input('Enter a number: '))
Numb3 = int(input('Enter a number: '))
if Numb1 > Numb2 and Numb1 > Numb3:
    print(Numb1)
elif  Numb2 > Numb1 and Numb2 > Numb3:
    print(Numb2)
else:
    print(Numb3)

Enter a number: 11
Enter a number: 24
Enter a number: 57
57


# Q8 : Checking Multiple

In [ ]:
number2 = int(input('Enter a number: '))
if number2 % 7 == 0:
    print('True')
else:
    print('False')

Enter a number: 49
True


# Q9

In [ ]:
fav_m1 = input('Enter your fav movie: ')
fav_m2 = input('Enter your fav movie: ')
fav_m3 = input('Enter your fav movie: ')
li = [fav_m1,fav_m2,fav_m3]
print(li)

Enter your fav movie: srl
Enter your fav movie: kk
Enter your fav movie: ar
['srl', 'kk', 'ar']


# Q10


In [ ]:
li1 = [1,2,3,2,1]
li2 = li1.copy()
li2.reverse()
if li1 == li2:
    print('True')
else:
    print('False')

li1.count(1)
li1.sort()
print(li1)

True
[1, 1, 2, 2, 3]


# Q11

In [ ]:
dict1 = {
    'table' :{
        'M1':'a piece of furniture',
        'M2':'listt of facts & figures'
     } ,
    'cat' : 'a small animal'
}
print(dict1)

{'table': {'M1': 'a piece of furniture', 'M2': 'listt of facts & figures'}, 'cat': 'a small animal'}


#Q12


In [ ]:
for i in range (0,3):
  for j in range (0,i):
    i = input('enter subject: ')
    j = input('enter marks: ')
    dict2[i]=j
print(dict2)

enter subject: m
enter marks: 2
enter subject: n
enter marks: 4
enter subject: b
enter marks: 4
{'j': 'j', 'm': '2', 'n': '4', 'b': '4'}


#Q13

In [ ]:
set1 = {9,'9.0'}
print (set1)

{9, '9.0'}


#Q14

In [ ]:
i = 1
while i <= 10:
  print(i)
  i+=1

1
2
3
4
5
6
7
8
9
10


#Q15

In [ ]:
i = 100
while i >= 0:
  print(i)
  i-=1

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0


#Q16

In [ ]:
i = 1
while i <=10:
  print(i**2)
  i+=1

1
4
9
16
25
36
49
64
81
100


#Q17

In [ ]:
tup = (1,4,9,16,25,36,49,64,81,100)
x = int(input('Enter a number: '))
count= 0
while len(tup) > count:
  if (x == tup[count]):
    print (count)
  count+=1

Enter a number: 25
4


#Q18

In [ ]:
x = int(input('Enter a number: '))
for i in range (1,11):
  print(f"{x}X{i} :",x*i)

Enter a number: 5
5X1 : 5
5X2 : 10
5X3 : 15
5X4 : 20
5X5 : 25
5X6 : 30
5X7 : 35
5X8 : 40
5X9 : 45
5X10 : 50


#Q19

In [ ]:
count = 1
product = 1
n = int(input('Enter a number: '))
while count <= n:
  product = product*count
  count+=1
print(product)

Enter a number: 5
120


#Q20

In [ ]:
count = 1
fact = 1
n = int(input('Enter a number: '))
for i in range (0,n):
   fact = fact*count
   count+=1
print(fact)

Enter a number: 5
120


#Q21


In [ ]:
a = 0
b = 1
x = int(input("enter a num: "))
for i in range (x):
  print(a)
  a , b = b,a+b


enter a num: 5
0
1
1
2
3


# Function

In [ ]:
def len_list(x):
  return len(x)
  print(len(x))

len_list([1,2,3,4,5,6])

6

In [ ]:
def same_line(li):
  for i in range (0,len(li)):
    print(li[i],end = " ")

listt = [1,2,3,6,4,5]
same_line(listt)

1 2 3 6 4 5 

#Q22

In [ ]:
def fac(n):
  m = 1
  for i in range(1,n+1):
    m *= i
  print(m)
a = int(input('Enter a number: '))
fac(a)

Enter a number: 5
120


In [ ]:
def con(usd):
  inr = usd * 80
  print(inr)

con(4)

320


# Practice Questions

# You are provided with a list of student scores in a class. Perform the following operations:

#Find and display the highest score in the class.
#Calculate and print the average score of the class.
#Identify and display the names of students who scored above a certain threshold (e.g., 80).
#Sort and display the student names in alphabetical order.

In [ ]:
s_names = ["Al", "Bob marley", "Charlie Cox", "David Miller", "Emma watson"]
scores = [75, 92, 80, 88, 95]

highest_score = max(scores)
print(highest_score)

avg_score = sum(scores) / len(scores)
print(average_score)

threshold = 85
above_threshold = [n for n, s in zip(s_names, scores) if s > threshold]
print(above_threshold)

sorted_names = sorted(s_names)
print(sorted_names)

Highest Score : 95
Average Score : 86.0
Students scoring above 85: ['Bob marley', 'David Miller', 'Emma watson']
Student Names in alph order: ['Al', 'Bob marley', 'Charlie Cox', 'David Miller', 'Emma watson']


# Write a program to generate two lists using list comprehension. The first list should contain the squares of numbers from 1 to 10, and the second list should contain the cubes of the same numbers.



In [ ]:
squares = [x**2 for x in range(1, 11)]
cubes = [x**3 for x in range(1, 11)]

print(squares)
print(cubes)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


# Given a list of numbers, create a new list that contains only the positive numbers from the original list. Implement this using list comprehension.

In [ ]:
numbers = [-15, 23, -18, 40, -22, 47, -1, 6]
p_numbers = [num for num in numbers if num > 0]
print("Positive Numbers:", p_numbers)

Positive Numbers: [23, 40, 47, 6]


# You have a list of student names. Implement a program to sort the names alphabetically and display the sorted list.



In [ ]:
s_names = ["Al", "David Miller", "Emma watson", "Bob marley", "Charlie Cox"]
s_names.sort()
print(s_names)

['Al', 'Bob marley', 'Charlie Cox', 'David Miller', 'Emma watson']


# You are managing student course enrollments, and each course has a unique identifier, a list of enrolled students, and their corresponding grades. Implement a program using advanced tuple operations to perform the following:

##Create a tuple for a course containing its identifier, a list of enrolled students, and their grades.
##Display the course information, including the average grade.
##Identify and display the student with the highest grade in the course.
##Update the grade of a specific student.

In [ ]:
c_data = ("CS101", ["Alice", "Bob", "Charlie"], [90, 85, 92])
c_id, students, grades = c_data
average_grade = sum(grades) / len(grades)
print(f"Students: {students}\nGrades: {grades}\nAverage Grade: {average_grade}")

highest = students[grades.index(max(grades))]
print(f"highest score: {highest}")

upd_grades = list(grades)
upd_grades[1] = 88
print(f"Students: {students}\nGrades: {upd_grades}\nAverage Grade: {average_grade}")

Students: ['Alice', 'Bob', 'Charlie']
Grades: [90, 85, 92]
Average Grade: 89.0
highest score: Charlie
Students: ['Alice', 'Bob', 'Charlie']
Grades: [90, 88, 92]
Average Grade: 89.0


# You have a list of student names, their ages, and their grades. Implement a program using tuple comprehension and filtering to perform the following:

##Create a list of tuples where each tuple contains a student’s name, age, and grade.
##Display the list of student tuples.
##Filter and display only the information of students who are above a certain age.

In [ ]:
names = ["Alice", "Bob", "Charlie", "David"]
ages = [20, 22, 19, 21]
grades = [85, 90, 78, 92]

s_info = [(name, age, grade) for name, age, grade in zip(names, ages, grades)]
print("List:", s_info)

Above_age = [(name, age, grade) for name, age, grade in s_info if age > 20]
print("Age greater than 20:", Above_age)

List: [('Alice', 20, 85), ('Bob', 22, 90), ('Charlie', 19, 78), ('David', 21, 92)]
Age greater than 20: [('Bob', 22, 90), ('David', 21, 92)]


# You have a list of employees, and each employee is represented as a tuple containing their name, hourly rate, and hours worked. Implement a program using tuple unpacking and functions to perform the following:

##Calculate and display the total salary for each employee.
##Identify and display the employee with the highest total salary.
##Display the average total salary of all employees.

In [ ]:
employees = [("Ram", 20, 40), ("Shyam", 25, 35), ("Babu Rao", 18, 50)]
def calculate_TS(rate, hours):
    return rate * hours

t_salaries = [calculate_TS(rate, hours) for _, rate, hours in employees]
print("Total Salaries:", t_salaries)

best_employee = employees[t_salaries.index(max(t_salaries))]
print(best_employee)

avg_sal = sum(t_salaries) / len(employees)
print( avg_sal)

Total Salaries: [800, 875, 900]
('Babu Rao', 18, 50)
858.3333333333334


#You have a dictionary where the keys are student names, and the values are tuples containing their scores in three different subjects. Implement a program using tuple and dictionary integration to perform the following:

##Display the student names and their average scores.
##Identify and display the student with the highest average score.
##Display the average scores for each subject.

In [ ]:
dictt = {"A": (85, 90, 92), "B": (78, 85, 88), "C": (90, 92, 95)}
avg_scores = {name: sum(scores) / len(scores) for name, scores in dictt.items()}
print(avg_scores)

h_avg_score = max(avg_scores, key=avg_scores.get)
print(h_avg_score)



{'A': 89.0, 'B': 83.66666666666667, 'C': 92.33333333333333}
C


### You are provided with a dictionary containing employee names and their corresponding monthly salaries. Find and display the highest salary in the company. Calculate and print the average salary of all employees. Identify and display the names of employees who earn above a certain threshold (e.g., $5000). Sort and display the employee names in alphabetical order.​

In [ ]:
employees = {'Ram': 6000,'Bovan': 9500,'Charu': 200,'Daman': 4600,'Sham': 7500}
h_salary = max(employees.values())
print(h_salary)

avg_salary = sum(employees.values()) / len(employees)
print(avg_salary)

threshold = 5000
above_threshold = [name for name, salary in employees.items() if salary > threshold]
print(above_threshold)

sorted = sorted(employees.keys())
print(sorted)

9500
5560.0
['Ram', 'Bovan', 'Sham']
['Bovan', 'Charu', 'Daman', 'Ram', 'Sham']


# Numpy

In [ ]:
import numpy as np

arr_1D = np.array([1, 2, 3, 4, 5])
print("1D Array :",arr_1D)

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array :",arr_2D)

1D Array : [1 2 3 4 5]
2D Array : [[1 2 3]
 [4 5 6]]


## List VS Numpy Array

In [ ]:
py_list = [1,2,3]
np_arr = np.array([1,2,3])

print(py_list * 2)
print(np_arr * 2) # 2d array has element wise multiplication

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range (1000)]
print(time.time()-start)

start2 = time.time()
#np_arr = np.array([i*2 for i in range (1000)])
np_arr = np.arange(1000)*2
print(time.time()-start2)

0.00025081634521484375
0.0007467269897460938


## Creating Array from scratch

In [ ]:
zeros = np.zeros((2,3)) # 2,3 is order i.e rows and column
print(zeros)

ones = np.ones((2,3))
print(ones)

random = np.random.random((3,3))
print(random * 10)

full = np.full((2,3),7) # array of order 2 x 3 with 7 as all elements
print(full)

empty = np.empty((2,3))
print(empty)

random2 = np.random.randint((2,3))
print(random2)

seq = np.arange(2,22,2)
print(seq)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9.73745786 3.91995775 5.08819324]
 [5.79743386 1.83609853 0.76548867]
 [4.36140174 9.91874148 2.53530371]]
[[7 7 7]
 [7 7 7]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 0]
[ 2  4  6  8 10 12 14 16 18 20]


## Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape", arr.shape)
print("Dimension ", arr.ndim)
print("Size", arr.size)
print("DType ", arr.dtype)

Shape (2, 3)
Dimension  2
Size 6
DType  int64


## Array Reshaping

In [ ]:
org = np.arange(12)
print(org)

reshaped = org.reshape(3,4)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

# flatten and ravel give same output but
# ravel (returns view, instead of copy) i.e doesnot change original
raveled = reshaped.ravel()
print("raveled array ", raveled)

transposed = np.transpose(reshaped) # change order r x c into c x r eg 2 x 3 becomes 3 x 2
print(transposed)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Array Operations

In [ ]:
array_ = np.array([1,2,3,4,5,6,7,8,9,0])
print(array_.sum())
print(array_.min())
print(array_.max())
print(array_.mean())
print(array_.std()) # standard deviation

print(array_[2:7])
print(array_[2:7:2])
print(array_[-4:])
print(array_[::-1])

array_2D = np.array([[1, 2, 5], [3, 4, 7]])
print(array_2D[1][1]) #Slicing
print(array_2D[1])
print(array_2D[:, 1])

45
0
9
4.5
2.8722813232690143
[3 4 5 6 7]
[3 5 7]
[7 8 9 0]
[0 9 8 7 6 5 4 3 2 1]
4
[3 4 7]
[2 4]


## Sorting

In [ ]:
arr = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr)
print(sorted_arr)

arr2d = np.array([[3, 1, 2], [5, 4, 6]])
sorted_arr2d = np.sort(arr2d, axis=0)
print(sorted_arr2d)


[1 2 3 4 5]
[[3 1 2]
 [5 4 6]]


## Filters


In [ ]:
array_num = np.array([1,2,3,4,5,6,7,8,9,0])
even_num = array_num[array_num % 2 == 0]
print(even_num)

# with Mask
mask = (array_num > 5)
print(array_num[mask])

[2 4 6 8 0]
[6 7 8 9]


In [ ]:
indices = [2,3,4,7]
print(array_num[indices])

where = array_num > 5
print(array_num[where])

[3 4 5 8]
[6 7 8 9]


In [ ]:
                    # Condition  , if true , false
condition = np.where(array_num > 5, 'True', 'False' ) #kinda like if else
print(condition)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'False']


## Adding and Removing

In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])
print(np.concatenate((arr1,arr2)))

arr1_2d = np.array([[1,2,3],[2,3,4]])
arr2_2d = np.array([[4,5,6]])
new_col = np.array([[6],[7]])
print(np.vstack((arr1_2d,arr2_2d)))
print(np.hstack((arr1_2d,new_col)))

#delete
print(np.delete(arr1,2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1 2 3]
 [2 3 4]
 [4 5 6]]
[[1 2 3 6]
 [2 3 4 7]]
[1 2 4 5 6]
